import streamlit as st
try:
    import utils
    import ai_insights
except ImportError:
    from project import utils, ai_insights

utils.inject_dashboard_style()
utils.setup_refresh()

utils.render_page_header(
    "AI Insights & Alerts",
    "Automated daily and weekly analysis generated by DigitalOcean Inference API."
)

st.markdown("<div class='dashboard-card small'><div class='dashboard-card-title'>AI insights status</div><p>Generate fresh automated summaries or review the latest daily and weekly intelligence.</p></div>", unsafe_allow_html=True)

col1, col2 = st.columns([3, 1])
with col1:
    st.markdown("### Latest AI Analysis")
with col2:
    if st.button("Generate Daily Insight Now", use_container_width=True):
        with st.spinner("Analyzing dashboard and generating insight..."):
            res = ai_insights.generate_insight("daily")
            if res:
                st.success("Generated successfully!")
                st.rerun()
            else:
                st.error("Generation failed. Check console logs.")

tab1, tab2 = st.tabs(["Daily Update", "Weekly Summary"])

with tab1:
    daily = ai_insights.get_latest_insight("daily")
    if daily:
        ist_time = daily.timestamp.replace(tzinfo=utils.IST_TZ) if daily.timestamp.tzinfo is None else daily.timestamp.astimezone(utils.IST_TZ)
        st.markdown("<div class='dashboard-card small'><div class='dashboard-card-title'>Daily insight summary</div></div>", unsafe_allow_html=True)
        card_cols = st.columns(3)
        card_cols[0].metric("Daily Insight", "Ready")
        card_cols[1].metric("Generated", ist_time.strftime("%d %b %H:%M"))
        card_cols[2].metric("Status", "Live analytics")
        st.caption("Generated on: " + ist_time.strftime("%Y-%m-%d %H:%M IST"))
        st.markdown(daily.content)
    else:
        st.info("No daily insight has been generated yet. Click the button above to generate one.")

with tab2:
    weekly = ai_insights.get_latest_insight("weekly")
    if weekly:
        ist_time = weekly.timestamp.replace(tzinfo=utils.IST_TZ) if weekly.timestamp.tzinfo is None else weekly.timestamp.astimezone(utils.IST_TZ)
        st.markdown("<div class='dashboard-card small'><div class='dashboard-card-title'>Weekly insight summary</div></div>", unsafe_allow_html=True)
        card_cols = st.columns(3)
        card_cols[0].metric("Weekly Insight", "Ready")
        card_cols[1].metric("Generated", ist_time.strftime("%d %b %H:%M"))
        card_cols[2].metric("Status", "Trend summary")
        st.caption("Generated on: " + ist_time.strftime("%Y-%m-%d %H:%M IST"))
        st.markdown(weekly.content)
    else:
        if st.button("Generate Weekly Summary Now", key="btn_weekly"):
            with st.spinner("Generating weekly summary..."):
                res = ai_insights.generate_insight("weekly")
                if res:
                    st.success("Generated successfully!")
                    st.rerun()
                else:
                    st.error("Generation failed.")
        st.info("No weekly summary available yet.")
